POST http://127.0.0.1:8000/demo
Accept: application/json

{
    "ENCODEPARAM": "CUbIpSchI1C90zBRJi0ee7ORbb9u013HCnmO3eVkaapX23WpB4OMi5Yu/D3WJi96J3o0fkbwPycM9cHAa5WhEtEOQActyggdRpuVQmwyotwgn0hou/WXJgVDJ/AfCWSmPgtPb1KaHW0kI7TM2HOlebSVmvV2OBd5feTw2WB8+a3XGfckBzES+5EUILZst+Jn6HVTkTm06HZa/3koqkRdMvH7IsxGyswlKknHZ975ZC3s9+DMnwzGqJ7raDI6wYsxFi8thhfDU9z3Ruz64GDJKDoLLCKS9fOmFbiAnPi6Gk0hUAHQYPwo/D7OJKWAkJ3IyDGCziyWHqdbwsQEHmJgYzHcFhp8zJuwNDtL1L4C82kn7C8QF2lkAVKJrXhQNcU8FL1u8BXkrPrn/P3PqQoKFYaaPGdJ9MyiISvloEUH1u+SpVgBu5YsaAWNpiwy3AHGLuONPJCafCo4Zf43RkFWw/IqC3inzD17akhY6Ea8iuk="
}
###
POST http://127.0.0.1:8000/user
Accept: application/json

{
  "ENCODEPARAM": "CUbIpSchI1C90zBRJi0eexO/HzddThCwW1T4XuKIr+tUIane0KeIzm08AaW2y12xonIBOAfnMLckkIreG/m/oKb6n6J4drwLdUlOVTpLoUe3CEKOb0ufJMd2z2haK/Pjc53Q0yW4aM+NzB8HX+s3VQg8NyYdOdGCBkGuwVsJ4tbnIIk4k36aCOnr0TgJpWt1QTzNyYNfR1cnBJpSrunmAvy0y/E0Rhz4LQiRQUnkzYDJ9qF6Eqsr/PbdDF+R+be1TlTcapWycitlHHB48hKtIqXBIRpvGCIGNYPmByMKx64WUvXhBJJoU6vm6RQDvhgbee0VTYMKe/77nActII5LkfQUDeGVIUiWOhYuadF/URgjSRxRVTc8/M/ldBYvAMR8FZewie2/sqoGZJ6artkwJupbbSHYreah16yqcJ6N/3zgqvcF6fUR8LmApjnOyZ1ybRxQj4g1sVrykw5nAdh8/NRLAN2aZCl/bbpD4DzhJ7CqjaZTFiMz8uakosbesBH8BSdTHTXkEhf2lr7Nf/3GZnJAN8aWZ7O1Vlhdvdo869CQ/aZzY0/LJIa+GR3HZew0D2J8Xv+KKRyao1dmVBC7lpGPZ6o/I/qt/lLz0R46LR8="
}